const languages = [
    { code: 'ab', name: 'Abkhaz', native: 'аҧсуа' },
    { code: 'aa', name: 'Afar', native: 'Afaraf' },
    { code: 'af', name: 'Afrikaans', native: 'Afrikaans' },
    { code: 'ak', name: 'Akan', native: 'Akan' },
    { code: 'sq', name: 'Albanian', native: 'Shqip' },
    { code: 'am', name: 'Amharic', native: 'አማርኛ' },
    { code: 'ar', name: 'Arabic', native: 'العربية' },
    { code: 'an', name: 'Aragonese', native: 'Aragonés' },
    { code: 'hy', name: 'Armenian', native: 'Հայերեն' },
    { code: 'as', name: 'Assamese', native: 'অসমীয়া' },
    { code: 'av', name: 'Avaric', native: 'авар мацӀ, магӀарул  мацӀ' },
    { code: 'ae', name: 'Avestan', native: 'avesta' },
    { code: 'ay', name: 'Aymara', native: 'aymar aru' },
    { code: 'az', name: 'Azerbaijani', native: 'azərbaycan dili' },
    { code: 'bm', name: 'Bambara', native: 'bamanankan' },
    { code: 'ba', name: 'Bashkir', native: 'башҡорт теле' },
    { code: 'eu', name: 'Basque', native: 'euskara, euskera' },
    { code: 'be', name: 'Belarusian', native: 'Беларуская' },
    { code: 'bn', name: 'Bengali', native: 'বাংলা' },
    { code: 'bh', name: 'Bihari', native: 'भोजपुरी' },
    { code: 'bi', name: 'Bislama', native: 'Bislama' },
    { code: 'bs', name: 'Bosnian', native: 'bosanski jezik' },
    { code: 'br', name: 'Breton', native: 'brezhoneg' },
    { code: 'bg', name: 'Bulgarian', native: 'български език' },
    { code: 'my', name: 'Burmese', native: 'ဗမာစာ' },
    { code: 'ca', name: 'Catalan', native: 'Català' },
    { code: 'ch', name: 'Chamorro', native: 'Chamoru' },
    { code: 'ce', name: 'Chechen', native: 'нохчийн мотт' },
    { code: 'ny', name: 'Chichewa', native: 'chiCheŵa, chinyanja' },
    { code: 'zh', name: 'Chinese', native: '中文 (Zhōngwén), 汉语, 漢語' },
    { code: 'cv', name: 'Chuvash', native: 'чӑваш чӗлхи' },
    { code: 'kw', name: 'Cornish', native: 'Kernewek' },
    { code: 'co', name: 'Corsican', native: 'corsu, lingua corsa' },
    { code: 'cr', name: 'Cree', native: 'ᓀᐦᐃᔭᐍᐏᐣ' },
    { code: 'hr', name: 'Croatian', native: 'hrvatski' },
    { code: 'cs', name: 'Czech', native: 'česky, čeština' },
    { code: 'da', name: 'Danish', native: 'dansk' },
    { code: 'dv', name: 'Divehi', native: 'ދިވެހި' },
    { code: 'dz', name: 'Bhutani', native: '' },
    { code: 'nl', name: 'Dutch', native: 'Nederlands, Vlaams' },
    { code: 'en', name: 'English', native: 'English' },
    { code: 'eo', name: 'Esperanto', native: 'Esperanto' },
    { code: 'et', name: 'Estonian', native: 'eesti, eesti keel' },
    { code: 'ee', name: 'Ewe', native: 'Eʋegbe' },
    { code: 'fo', name: 'Faroese', native: 'føroyskt' },
    { code: 'fj', name: 'Fijian', native: 'vosa Vakaviti' },
    { code: 'fi', name: 'Finnish', native: 'suomi, suomen kieli' },
    { code: 'fr', name: 'French', native: 'français, langue française' },
    { code: 'ff', name: 'Fula', native: 'Fulfulde, Pulaar, Pular' },
    { code: 'gl', name: 'Galician', native: 'Galego' },
    { code: 'ka', name: 'Georgian', native: 'ქართული' },
    { code: 'de', name: 'German', native: 'Deutsch' },
    { code: 'el', name: 'Greek', native: 'Ελληνικά' },
    { code: 'gn', name: 'Guaran&iacute;', native: 'Avañeẽ' },
    { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
    { code: 'ht', name: 'Haitian', native: 'Kreyòl ayisyen' },
    { code: 'ha', name: 'Hausa', native: 'Hausa, هَوُسَ' },
    { code: 'he', name: 'Hebrew', native: 'עברית' },
    { code: 'hz', name: 'Herero', native: 'Otjiherero' },
    { code: 'hi', name: 'Hindi', native: 'हिन्दी, हिंदी' },
    { code: 'ho', name: 'Hiri Motu', native: 'Hiri Motu' },
    { code: 'hu', name: 'Hungarian', native: 'Magyar' },
    { code: 'ia', name: 'Interlingua', native: 'Interlingua' },
    { code: 'id', name: 'Indonesian', native: 'Bahasa Indonesia' },
    { code: 'ie', name: 'Interlingue', native: '' },
    { code: 'ga', name: 'Irish', native: 'Gaeilge' },
    { code: 'ig', name: 'Igbo', native: 'Asụsụ Igbo' },
    { code: 'ik', name: 'Inupiaq', native: 'Iñupiaq, Iñupiatun' },
    { code: 'io', name: 'Ido', native: 'Ido' },
    { code: 'is', name: 'Icelandic', native: 'Íslenska' },
    { code: 'it', name: 'Italian', native: 'Italiano' },
    { code: 'iu', name: 'Inuktitut', native: 'ᐃᓄᒃᑎᑐᑦ' },
    { code: 'ja', name: 'Japanese', native: '日本語 (にほんご／にっぽんご)' },
    { code: 'jv', name: 'Javanese', native: 'basa Jawa' },
    { code: 'kl', name: 'Greenlandic', native: '' },
    { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
    { code: 'kr', name: 'Kanuri', native: 'Kanuri' },
    { code: 'ks', name: 'Kashmiri', native: 'कश्मीरी, كشميري‎' },
    { code: 'kk', name: 'Kazakh', native: 'Қазақ тілі' },
    { code: 'km', name: 'Khmer', native: 'ភាសាខ្មែរ' },
    { code: 'ki', name: 'Kikuyu', native: 'Gĩkũyũ' },
    { code: 'rw', name: 'Kinyarwanda', native: 'Ikinyarwanda' },
    { code: 'ky', name: 'Kirghiz', native: 'кыргыз тили' },
    { code: 'kv', name: 'Komi', native: 'коми кыв' },
    { code: 'kg', name: 'Kongo', native: 'KiKongo' },
    { code: 'ko', name: 'Korean', native: '한국어 (韓國語), 조선말 (朝鮮語)' },
    { code: 'ku', name: 'Kurdish', native: 'Kurdî, كوردی‎' },
    { code: 'kj', name: 'Kwanyama', native: 'Kuanyama' },
    { code: 'la', name: 'Latin', native: 'latine, lingua latina' },
    { code: 'lb', name: 'Luxembourgish', native: 'Lëtzebuergesch' },
    { code: 'lg', name: 'Luganda', native: 'Luganda' },
    { code: 'li', name: 'Limburgish', native: 'Limburgs' },
    { code: 'ln', name: 'Lingala', native: 'Lingála' },
    { code: 'lo', name: 'Lao', native: 'ພາສາລາວ' },
    { code: 'lt', name: 'Lithuanian', native: 'lietuvių kalba' },
    { code: 'lu', name: 'Luba-Katanga', native: '' },
    { code: 'lv', name: 'Latvian', native: 'latviešu valoda' },
    { code: 'gv', name: 'Manx', native: 'Gaelg, Gailck' },
    { code: 'mk', name: 'Macedonian', native: 'македонски јазик' },
    { code: 'mg', name: 'Malagasy', native: 'Malagasy fiteny' },
    { code: 'ms', name: 'Malay', native: 'bahasa Melayu, بهاس ملايو‎' },
    { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
    { code: 'mt', name: 'Maltese', native: 'Malti' },
    { code: 'mi', name: 'Maori', native: 'te reo Māori' },
    { code: 'mr', name: 'Marathi', native: 'मराठी' },
    { code: 'mh', name: 'Marshallese', native: 'Kajin M̧ajeļ' },
    { code: 'mn', name: 'Mongolian', native: 'монгол' },
    { code: 'na', name: 'Nauru', native: 'Ekakairũ Naoero' },
    { code: 'nv', name: 'Navajo', native: 'Diné bizaad, Dinékʼehǰí' },
    { code: 'nb', name: 'Norwegian Bokmål', native: 'Norsk bokmål' },
    { code: 'nd', name: 'North Ndebele', native: 'isiNdebele' },
    { code: 'ne', name: 'Nepali', native: 'नेपाली' },
    { code: 'ng', name: 'Ndonga', native: 'Owambo' },
    { code: 'nn', name: 'Norwegian Nynorsk', native: 'Norsk nynorsk' },
    { code: 'no', name: 'Norwegian', native: 'Norsk' },
    { code: 'ii', name: 'Nuosu', native: 'ꆈꌠ꒿ Nuosuhxop' },
    { code: 'nr', name: 'South Ndebele', native: 'isiNdebele' },
    { code: 'oc', name: 'Occitan', native: 'Occitan' },
    { code: 'oj', name: 'Ojibwe', native: 'ᐊᓂᔑᓈᐯᒧᐎᓐ' },
    { code: 'cu', name: 'Old Church Slavonic', native: 'ѩзыкъ словѣньскъ' },
    { code: 'om', name: 'Oromo', native: 'Afaan Oromoo' },
    { code: 'or', name: 'Oriya', native: 'ଓଡ଼ିଆ' },
    { code: 'os', name: 'Ossetian', native: 'ирон æвзаг' },
    { code: 'pa', name: 'Panjabi', native: 'ਪੰਜਾਬੀ, پنجابی‎' },
    { code: 'pi', name: 'Pali', native: 'पाऴि' },
    { code: 'fa', name: 'Persian', native: 'فارسی' },
    { code: 'pl', name: 'Polish', native: 'polski' },
    { code: 'ps', name: 'Pashto', native: 'پښتو' },
    { code: 'pt', name: 'Portuguese', native: 'Português' },
    { code: 'qu', name: 'Quechua', native: 'Runa Simi, Kichwa' },
    { code: 'rm', name: 'Romansh', native: 'rumantsch grischun' },
    { code: 'rn', name: 'Kirundi', native: 'kiRundi' },
    { code: 'ro', name: 'Romanian', native: 'română' },
    { code: 'ru', name: 'Russian', native: 'русский язык' },
    { code: 'sa', name: 'Sanskrit', native: 'संस्कृतम्' },
    { code: 'sc', name: 'Sardinian', native: 'sardu' },
    { code: 'sd', name: 'Sindhi', native: 'सिन्धी, سنڌي، سندھی‎' },
    { code: 'se', name: 'Northern Sami', native: 'Davvisámegiella' },
    { code: 'sm', name: 'Samoan', native: 'gagana faa Samoa' },
    { code: 'sg', name: 'Sango', native: 'yângâ tî sängö' },
    { code: 'sr', name: 'Serbian', native: 'српски језик' },
    { code: 'gd', name: 'Scottish Gaelic', native: 'Gàidhlig' },
    { code: 'sn', name: 'Shona', native: 'chiShona' },
    { code: 'si', name: 'Sinhala', native: 'සිංහල' },
    { code: 'sh', name: 'Serbo-Croatian', native: '' },
    { code: 'sk', name: 'Slovak', native: 'slovenčina' },
    { code: 'sl', name: 'Slovene', native: 'slovenščina' },
    { code: 'so', name: 'Somali', native: 'Soomaaliga, af Soomaali' },
    { code: 'st', name: 'Southern Sotho', native: 'Sesotho' },
    { code: 'es', name: 'Spanish', native: 'español, castellano' },
    { code: 'su', name: 'Sundanese', native: 'Basa Sunda' },
    { code: 'sw', name: 'Swahili', native: 'Kiswahili' },
    { code: 'ss', name: 'Swati', native: 'SiSwati' },
    { code: 'sv', name: 'Swedish', native: 'svenska' },
    { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
    { code: 'te', name: 'Telugu', native: 'తెలుగు' },
    { code: 'tg', name: 'Tajik', native: 'тоҷикӣ, toğikī, تاجیکی‎' },
    { code: 'th', name: 'Thai', native: 'ไทย' },
    { code: 'ti', name: 'Tigrinya', native: 'ትግርኛ' },
    { code: 'bo', name: 'Tibetan', native: 'བོད་ཡིག' },
    { code: 'tk', name: 'Turkmen', native: 'Türkmen, Түркмен' },
    { code: 'tl', name: 'Tagalog', native: 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔' },
    { code: 'tn', name: 'Tswana', native: 'Setswana' },
    { code: 'to', name: 'Tonga', native: 'faka Tonga' },
    { code: 'tr', name: 'Turkish', native: 'Türkçe' },
    { code: 'ts', name: 'Tsonga', native: 'Xitsonga' },
    { code: 'tt', name: 'Tatar', native: 'татарча, tatarça, تاتارچا‎' },
    { code: 'tw', name: 'Twi', native: 'Twi' },
    { code: 'ty', name: 'Tahitian', native: 'Reo Tahiti' },
    { code: 'ug', name: 'Uighur', native: 'Uyƣurqə, ئۇيغۇرچە‎' },
    { code: 'uk', name: 'Ukrainian', native: 'українська' },
    { code: 'ur', name: 'Urdu', native: 'اردو' },
    { code: 'uz', name: 'Uzbek', native: 'zbek, Ўзбек, أۇزبېك‎' },
    { code: 've', name: 'Venda', native: 'Tshivenḓa' },
    { code: 'vi', name: 'Vietnamese', native: 'Tiếng Việt' },
    { code: 'vo', name: 'Volapük', native: 'Volapük' },
    { code: 'wa', name: 'Walloon', native: 'Walon' },
    { code: 'cy', name: 'Welsh', native: 'Cymraeg' },
    { code: 'wo', name: 'Wolof', native: 'Wollof' },
    { code: 'fy', name: 'Frisian (Western)', native: 'Frysk' },
    { code: 'xh', name: 'Xhosa', native: 'isiXhosa' },
    { code: 'yi', name: 'Yiddish', native: 'ייִדיש' },
    { code: 'yo', name: 'Yoruba', native: 'Yorùbá' },
    { code: 'za', name: 'Zhuang', native: 'Saɯ cueŋƅ, Saw cuengh' },
    { code: 'zu', name: 'Zulu', native: '' },
    { code: 'alt', name: 'Southern Altai' },
    { code: 'ami', name: 'Amis' },
    { code: 'anp', name: 'Angika' },
    { code: 'arz', name: 'Arabic (Egyptian)' },
    { code: 'azb', name: 'South Azerbaijani' },
    { code: 'ast', name: 'Asturian' },
    { code: 'ace', name: 'Achinese' },
    { code: 'ady', name: 'Adyghe' },
    { code: 'als', name: 'Alemannic' },
    { code: 'ang', name: 'Anglo-Saxon' },
    { code: 'arc', name: 'Aramaic' },
    { code: 'ary', name: 'Arabic (Moroccan)' },
    { code: 'atj', name: 'Atikamekw' },
    { code: 'avk', name: 'Kotava' },
    { code: 'awa', name: 'Awadhi' },
    { code: 'bar', name: 'Bavarian' },
    { code: 'ban', name: 'Balinese' },
    { code: 'bbc', name: 'Toba Batak' },
    { code: 'bcl', name: 'Bikol' },
    { code: 'bew', name: 'Betawi' },
    { code: 'bjn', name: 'Banjarese' },
    { code: 'blk', name: "Pa'O" },
    { code: 'bpy', name: 'Bishnupriya Manipuri' },
    { code: 'btm', name: 'Mandailing Batak' },
    { code: 'bug', name: 'Buginese' },
    { code: 'bxr', name: 'Russia Buriat' },
    { code: 'cdo', name: 'Chinese (Min Dong)' },
    { code: 'ceb', name: 'Cebuano' },
    { code: 'cho', name: 'Choctaw' },
    { code: 'chr', name: 'Cherokee' },
    { code: 'chy', name: 'Cheyenne' },
    { code: 'ckb', name: 'Kurdish (Sorani)' },
    { code: 'crh', name: 'Crimean Tatar' },
    { code: 'csb', name: 'Kashubian' },
    { code: 'dag', name: 'Dagbani' },
    { code: 'din', name: 'Dinka' },
    { code: 'dga', name: 'Dagaare' },
    { code: 'diq', name: 'Dimli' },
    { code: 'dsb', name: 'Lower Sorbian' },
    { code: 'dtp', name: 'Dusun' },
    { code: 'dty', name: 'Doteli' },
    { code: 'eml', name: 'Emiliano-Romagnolo' },
    { code: 'ext', name: 'Extremaduran' },
    { code: 'fat', name: 'Fante ' },
    { code: 'fon', name: 'Fon' },
    { code: 'frp', name: 'Franco-Provençal' },
    { code: 'frr', name: 'Frisian (Northern)' },
    { code: 'fur', name: 'Friulian' },
    { code: 'gag', name: 'Gagauz' },
    { code: 'gan', name: 'Chinese (Gan)' },
    { code: 'gcr', name: 'Guianese Creole French' },
    { code: 'glk', name: 'Gilaki' },
    { code: 'gom', name: 'Goan Konkani' },
    { code: 'gor', name: 'Gorontalo' },
    { code: 'got', name: 'Gothic' },
    { code: 'gpe', name: 'Ghanaian Pidgin English' },
    { code: 'guc', name: 'Wayuu' },
    { code: 'guw', name: 'Gun' },
    { code: 'hak', name: 'Chinese (Hakka)' },
    { code: 'haw', name: 'Hawaiian' },
    { code: 'hif', name: 'Hindi (Fiji)' },
    { code: 'hsb', name: 'Upper Sorbian' },
    { code: 'hyw', name: 'Armenian (Western)' },
    { code: 'igl', name: 'Igala' },
    { code: 'ilo', name: 'Ilokano' },
    { code: 'inh', name: 'Ingush' },
    { code: 'jam', name: 'Jamaican Creole English' },
    { code: 'jbo', name: 'Lojban' },
    { code: 'kaa', name: 'Kara-Kalpak' },
    { code: 'kab', name: 'Kabyle' },
    { code: 'kcg', name: 'Tyap' },
    { code: 'kbd', name: 'Kabardian' },
    { code: 'kbp', name: 'Kabiyè' },
    { code: 'koi', name: 'Komi-Permyak' },
    { code: 'krc', name: 'Karachay-Balkar' },
    { code: 'ksh', name: 'Ripuarian' },
    { code: 'lad', name: 'Ladino' },
    { code: 'lbe', name: 'Lak' },
    { code: 'lez', name: 'Lezghian' },
    { code: 'lfn', name: 'Lingua Franca Nova' },
    { code: 'lij', name: 'Ligurian' },
    { code: 'lld', name: 'Ladin' },
    { code: 'lmo', name: 'Lombard' },
    { code: 'ltg', name: 'Latgalian' },
    { code: 'mad', name: 'Madurese' },
    { code: 'mai', name: 'Maithili' },
    { code: 'mdf', name: 'Moksha' },
    { code: 'mhr', name: 'Mari (Eastern)' },
    { code: 'min', name: 'Minangkabau' },
    { code: 'mni', name: 'Manipuri' },
    { code: 'mnw', name: 'Mon' },
    { code: 'mrj', name: 'Mari (Western)' },
    { code: 'mwl', name: 'Mirandese' },
    { code: 'myv', name: 'Erzya' },
    { code: 'mzn', name: 'Mazanderani' },
    { code: 'nah', name: 'Nahuatl' },
    { code: 'nap', name: 'Neapolitan' },
    { code: 'nds', name: 'Low Saxon' },
    { code: 'new', name: 'Newar' },
    { code: 'nia', name: 'Nias' },
    { code: 'nov', name: 'Novial' },
    { code: 'nqo', name: "N'Ko" },
    { code: 'nrm', name: 'Norman' },
    { code: 'nso', name: 'Northern Sotho' },
    { code: 'olo', name: 'Livvi-Karelian' },
    { code: 'pag', name: 'Pangasinan' },
    { code: 'pam', name: 'Kapampangan' },
    { code: 'pap', name: 'Papiamentu' },
    { code: 'pcd', name: 'Picard' },
    { code: 'pcm', name: 'Nigerian Pidgin' },
    { code: 'pdc', name: 'Pennsylvania German' },
    { code: 'pfl', name: 'Pfaelzisch' },
    { code: 'pih', name: 'Norfolk' },
    { code: 'pms', name: 'Piedmontese' },
    { code: 'pnb', name: 'Panjabi (Western)' },
    { code: 'pnt', name: 'Pontic' },
    { code: 'pwn', name: 'Paiwan' },
    { code: 'rmy', name: 'Romani' },
    { code: 'rue', name: 'Rusyn' },
    { code: 'sah', name: 'Yakut' },
    { code: 'sat', name: 'Santali' },
    { code: 'scn', name: 'Sicilian' },
    { code: 'sco', name: 'Scots' },
    { code: 'shi', name: 'Tachelhit' },
    { code: 'shn', name: 'Shan' },
    { code: 'skr', name: 'Saraiki' },
    { code: 'smn', name: 'Inari Sami' },
    { code: 'srn', name: 'Sranan Tongo' },
    { code: 'stq', name: 'Frisian (Saterland)' },
    { code: 'szl', name: 'Silesian' },
    { code: 'szy', name: 'Sakizaya' },
    { code: 'tay', name: 'Atayal' },
    { code: 'tcy', name: 'Tulu' },
    { code: 'tet', name: 'Tetum' },
    { code: 'tly', name: 'Talysh' },
    { code: 'tpi', name: 'Tok Pisin' },
    { code: 'trv', name: 'Taroko' },
    { code: 'tum', name: 'Tumbuka' },
    { code: 'tyv', name: 'Tuvinian' },
    { code: 'udm', name: 'Udmurt' },
    { code: 'vec', name: 'Venetian' },
    { code: 'vep', name: 'Veps' },
    { code: 'vls', name: 'West Flemish' },
    { code: 'war', name: 'Waray' },
    { code: 'wuu', name: 'Chinese (Wu)' },
    { code: 'xal', name: 'Kalmyk' },
    { code: 'xmf', name: 'Megrelian' },
    { code: 'zea', name: 'Zeeuws' },
    { code: 'zgh', name: 'Standard Moroccan Amazigh' },
    { code: 'roa_tara', name: 'Tarantino' },
    { code: 'bat_smg', name: 'Samogitian' },
    { code: 'cbk_zam', name: 'Chavacano' },
    { code: 'fiu_vro', name: 'Võro' },
    { code: 'map_bms', name: 'Banyumasan' },
    { code: 'roa_rup', name: 'Aromanian' },
    { code: 'zh_classical', name: 'Chinese (Classical)' },
    { code: 'zh_min_nan', name: 'Chinese (Southern Min)' },
    { code: 'zh_yue', name: 'Cantonese' },
    { code: 'be_x_old', name: 'Belarusian (Classical)' },
    { code: 'nds_nl', name: 'Low Saxon (Dutch)' },
    { code: 'simple', name: 'English (Simple)' },
    { code: 'commons', name: 'Wikimedia Commons' },
    { code: 'species', name: 'Wikispecies' },
    { code: 'meta', name: 'Meta-Wiki' },
];

function languageNameFromCode(code) {
    let name = code;
    languages.forEach(function (language) {
        if (language.code === code) {
            name = language.name;
        }
    });
    return name;
}

export { languageNameFromCode };
